### ISSUE TITLE
Provide same API for single-thread and multi-thread

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx-rs#319]
I noticed there is a lot of duplicated methods with same names across different objects. See Device, Renderer and Graphics. When you write a library on top of gfx, you are forced to choose whether it should be single threaded of multi threaded.

For example, 'update_buffer' that takes a slice is missing for multi-threads. The solution is simple: It can copy the content of the buffer. Instead of allocating a new Vec you can reuse the same.

An idea is having one trait that gives you everything you need.

* Device could implement this trait and pass calls directly
* Renderer could implement this trait for multi-threading

**Comment by kvark** [comment]
Closing as fixed
