### ISSUE TITLE
Refactor ShaderParam using associated types

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#400]
We could hide the link type entirely, simplifying the interface and streamlining the batch usage.

**Comment by bjz** [comment]
\o/

**Comment by bvssvni** [comment]
Hey, what happened?

**Comment by bvssvni** [comment]
Oh, nice!

**Comment by kvark** [comment]
Actually, with this in we no longer need to generate a typedef in the macros. One can just say `RefBatch<YourStruct>` and be good with it.

**Comment by sectopod** [comment]
@kvark yeah, that's the end goal. I'm on it ;)

**Comment by bjz** [comment]
Merged now!
