### ISSUE TITLE
Have a way to build up batches in a pure way without needing a mutable reference to `self`.

### ISSUE THREAD

**Issue by bjz** [gfx-rs/gfx-rs#457]
Say I want to create a drawable thing with certain buffers and shaders. If I want to create a function to create meshes, slices, and batches, I need to have a mutable reference to ~~`self`~~ the `Device`. It would be nice to be able to build up a set of those device calls in a pure way and do it all at once to push the need for a mutable context to as high a layer as possible.

For example, currently I need to do something like this:

~~~rust
    let axis_mesh       = graphics.device.create_mesh(axis_thingy::VERTEX_DATA);
    let axis_slice      = axis_mesh.to_slice(gfx::Line);
    let axis_state      = gfx::DrawState::new().depth(gfx::state::LessEqual, true);
    let axis_batch: WorldBatch = graphics.make_batch(&program, &axis_mesh, axis_slice, &axis_state).unwrap();
~~~

I want a function like this that I can reuse without a mutable reference to the device context:

~~~rust
impl Axis {
    fn get_device_stuff() -> BatchBuilder { ... }
}
~~~

I don't know exactly how best to do this, but I think it is worth discussing.

**Comment by kvark** [comment]
You don't really need a mutable device to make batches, you only need it for resource creation. Closing as being abandoned. Please re-open if you face it again.

**Comment by bjz** [comment]
Closing because this is poorly specified. (I can't remember what my issue was, so that is a bad sign)

**Comment by bjz** [comment]
Oh, too slow!
