### ISSUE TITLE
Put gfx-rs on crates.io

### ISSUE THREAD

**Issue by palodequeso** [gfx-rs/gfx-rs#460]
I think this library is awesome, and should probably get registered on https://crates.io/
That is all.

**Comment by kvark** [comment]
Ok, I did a small research on this one. Here is what needs to be done by one of our project owners:
- make sure the version is set up, all meta-data is filled, and no excess files are included
- `cargo package` to ensure all the dependencies work
- `cargo owner --add` for me, @bjz, and @cmr
- `cargo publish` to upload it

**Comment by csherratt** [comment]
This might also require some small tweaks to the naming. `device` might need to be `gfx-device` for example.

**Comment by bjz** [comment]
We need all crates on crates.io - glfw is now, which was one barrier.

**Comment by bvssvni** [comment]
A tips for keeping the version on crates.io updated: Add version comments like https://github.com/PistonDevelopers/graphics/blob/master/Cargo.toml beneath the git link. Before publishing, uncomment them to verify the version is updated, and when publishing, comment the git link.
