### ISSUE TITLE
Make ShaderParam::Link copyable again

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#521]
Somewhere along the introduction of associated types to shader parameters, we lost `Copy` on the generated `Link` structure. This breaks https://github.com/PistonDevelopers/hematite/issues/181

We might want to test for it (in tests).

cc @sectopod @bvssvni @toqueteos

**Comment by bvssvni** [comment]
A `fn is_copy<T: Copy>() {}` in a unit test might suffice.

**Comment by bjz** [comment]
:+1:
