### ISSUE TITLE
Rename CommandBuffer to RenderBuffer

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#524]
Since this thing has both commands AND data, it makes less sense to name it `CommandBuffer`. The beauty of the `RenderBuffer` name is that it's populated by the `Renderer`. The downside is possible confusion with GL render buffers (which we call `Surface`).

**Comment by cmr** [comment]
I think this is a great idea.

--
Corey Richardson http://octayn.net/


On Wed, Feb 4, 2015, at 18:21, Dzmitry Malyshau wrote:
> Since this thing has both commands AND data, it makes less sense to
> name it CommandBuffer. The beauty of the RenderBuffer name is that
> it's populated by the Renderer. The downside is possible confusion
> with GL render buffers (which we call Surface).


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/gfx-rs/gfx-rs/issues/524

**Comment by csherratt** [comment]
how about `RenderQueue` that way you avoid the word buffer.

**Comment by kvark** [comment]
@csherratt `RenderQueue` is actually pretty good, but this is exactly how I name *actual* render queues (that have batches in them), so it's gonna conflict with higher-level stuff...

**Comment by csherratt** [comment]
`RendeList`?

**Comment by kvark** [comment]
My apologies to everyone. This is really lame. I just forgot how things are named.

Our `CommandBuffer` only carries commands, so it doesn't need a better name. The `Renderer` carries both the command buffer and the data buffer. Eventually, we'll make a `DataBuffer` trait, but this is a different story.
