### ISSUE TITLE
Detect when the depth/stencil test is used with a missing attachment

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#525]
We should return an error for these calls.

**Comment by kvark** [comment]
Ha, it turns out we eliminated all other sources of errors for the draw calls, so they don't return `Result` now. It is cool and dandy, but checking for the depth/stencil would require us to bring back the `Result` with those nasty `unwrap` calls in the user/example code. Perhaps, we don't want to rush with this decision.

**Comment by kvark** [comment]
@csherratt @bjz ideas?

I'd like to keep API clean (the less `unwrap` the better).. Putting a frame inside the draw call seems to be a little to extreme, especially since we are not sharing frames at all.

**Comment by bjz** [comment]
I think the general move is towards using `try!` instead of `unwrap`.
