### ISSUE TITLE
Implement GLFW/Glutin bridges as separate crates

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#529]
@dylanede:
> But you could provide a trait and then split integration into separate crates?
> Just seems a bit painful for everyone to reinvent the wheel when they first use gfx with any windowing system

Every gfx-rs app has several lines of code dedicated to window creation. We could simplify this by introducing "bridge" crates (aka `gfx_bridge_glfw`) under `gfx-rs`  organization that would allow:
  - one-line window creation
  - return the default frame buffer

See also: #515

Note: historically, we had glfw and glutin (later) integration from the start. At some point, we decided to isolate away from it. Looks like it's time to bring those back as separate crates.

**Comment by bjz** [comment]
What wheel are we talking about?

**Comment by kvark** [comment]
@bjz better integration with glfw and Glutin. We need to bring back those bridges for convenient window creation (as separate crates under gfx-rs organization). This would also make the default framebuffer creation safer (#530)

**Comment by bjz** [comment]
Yeah this would be good, and make sense in separate crates. :+1:

**Comment by bjz** [comment]
Could you clearly specify a list of the things we need in the issue description, based off #530?

**Comment by kvark** [comment]
@bjz better now?

**Comment by bjz** [comment]
Sounds great. Not sure about the naming, but we can bikeshed that some other time.

**Comment by kvark** [comment]
This is especially important now that we have `device.after_frame()`.
