### ISSUE TITLE
gfx_device_gl keeps re-building even with no changes

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#534]

**Comment by csherratt** [comment]
I can't reproduce this, but I have noticed this in other projects (with other none-dirty packages). Perhaps this is a bug in Cargo?

**Comment by kvark** [comment]
Hmm, I have the system date broken. Will double-check when it's fixed. Still weird that `gfx_device_gl` is the only crate being rebuilt... Closing for now.
