### ISSUE TITLE
Integrate with piston_image

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#561]
The task of loading an image into a gfx-rs texture can be streamlined. We could have a gfx_image repository here to provide some bridging functions.

**Comment by bvssvni** [comment]
There is a library used in Hematite: https://github.com/pistondevelopers/gfx_texture

**Comment by bvssvni** [comment]
Btw, it is also used in gfx_graphics.

**Comment by kvark** [comment]
@bvssvni thanks! It may need some work, but this is exactly what I wanted.
