### ISSUE TITLE
Slice kind mutates in draw call

### ISSUE THREAD

**Issue by mzmonsour** [gfx-rs/gfx-rs#581]
When a Slice is provided to a Renderer via the draw method, it mutates the kind (zeroing it out). This visibly breaks the cube example after the first frame.

Based on my debugging, I narrowed the mutation down to the line https://github.com/gfx-rs/gfx-rs/blob/master/src/render/lib.rs#L461

**Comment by csherratt** [comment]
This is related to https://github.com/gfx-rs/gfx-rs/issues/574 As it is caused by the same compiler bug.

**Comment by csherratt** [comment]
Thanks for narrowing this down @mzmonsour . I suspect putting a `.clone()` would work around this issue.

**Comment by mzmonsour** [comment]
That seems to fix it. Should I make a pull request for this?

**Comment by csherratt** [comment]
Yes, make a pull request. It would be appreciated.

**Comment by kvark** [comment]
I suppose calling `clone()` doesn't really hurt us, so will not need to change it back after Rust is fixed.
