### ISSUE TITLE
Docs are not updated

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#600]
reported by @MaikKlein :
> last build log https://travis-ci.org/gfx-rs/gfx-rs/builds/51983102
> "# the doc directory needs to be in the root for rust-ci mv target/doc doc"

**Comment by kvark** [comment]
Looks like it's still not fixed :(

**Comment by bvssvni** [comment]
This might be of help https://github.com/PistonDevelopers/piston/issues/845#issuecomment-75830856

**Comment by kvark** [comment]
Fixed by #677

**Comment by kvark** [comment]
Seems like it's not updated still.

**Comment by kvark** [comment]
Actually fixed by #714 
Docs are at http://gfx-rs.github.io/gfx-rs
