### ISSUE TITLE
Make `Device` inherit `Resources`

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx-rs#615]
The `Resources` trait only contains associated types and is used to tell what types is associated with a `Device`. Instead of having an associated `Resources` type, make `Device` inherit it. This will simplify the API quite a bit.

**Comment by bvssvni** [comment]
Seems that some part of the API depends on `Resources` being `Copy`.

**Comment by kvark** [comment]
:+1: if it's possible

**Comment by kvark** [comment]
This may conflict with #570, which has our strategic interest. I suppose let's not shuffle stuff too much until it's clear what the requirements for async resourcing are.

**Comment by kvark** [comment]
@bvssvni will it simplify the API? I briefly thought about it and didn't find any particular case that would be  helped. I believe `<D as Resources>` is not better than `D::Resources`.

**Comment by bvssvni** [comment]
I think we can close this, because the separation of device and resources fits better with the new architecture.
