### ISSUE TITLE
Replace type alias handles with structs

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx-rs#616]
I am not sure why `Handle` is abstracted here, perhaps normal structs can be used instead?

They map from `Resource::X` to `X` in the first argument which makes them hard to reason about.

**Comment by bvssvni** [comment]
Actually, the whole handle thing makes it unnecessary complex. Since all resources should be associated types, there is no need to add something that maps the associated types through a type alias.

Instead, could use traits to get the information directly from the associated resources.

**Comment by bvssvni** [comment]
In "gfx_device_gl" all the associated types are aliased to `GLuint`.

**Comment by bvssvni** [comment]
Whenever `Handle` is used in generic code, it is used for `RawBufferHandle`.

**Comment by bvssvni** [comment]
Error messages becomes clearer with structs, and we can get rid of `Handle` and `HandleFactory`.

**Comment by kvark** [comment]
@bvssvni could you mock up an example of what you propose, please? I can't figure out what you mean.

**Comment by bvssvni** [comment]
```Rust
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct ShaderHandle<R: Resources> {
    /// Name of shader.
    pub name: <R as Resources>::Shader,
    /// Info about shader.
    pub info: shade::Stage,
}
```

Instead of `Handle` and `HandleFactory`, just use structs.

**Comment by bvssvni** [comment]
However, if I succeed making all associated types directly, then these goes away.

**Comment by kvark** [comment]
@bvssvni I like that, :+1:
