### ISSUE TITLE
Move `MeshError` from "render/batch.rs" to "render/mesh.rs"

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx-rs#619]
Perhaps name it to `mesh::Error`?

`BatchError` could be named `batch::Error`.

**Comment by bvssvni** [comment]
- [ ] `CreateShadeError` => `shade:Error`
- [ ] `BatchError` => `batch::Error`
- [ ] `MeshError` => `mesh::Error`

**Comment by kvark** [comment]
Sounds good!

**Comment by kvark** [comment]
Fixed by #624. `CreateShaderError` will live a bit longer, I suppose.
