### ISSUE TITLE
Make the main frame to be safe

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#681]
1. Disallow creation by the user
  2. Disallow extraction/cloning of the attached surfaces
  3. Inherit the properties of the windowing system: 
    - size
    - MSAA
    - depth/stencil
    - sRGB

Since the current `Frame` is just a blank state, we can't just attach some (dummy) planes to it and call it a day, because that would fail p2.

Hence, polymorphism can't be achieved by mutating the struct. The only logical solution would be to use the `Frame` as a trait, thus leaving all mutation methods to be a part of the particular struct implementing it. The main frame will be absolutely opaque then. Going this route, we could also have `Frame` implemented for `Texture`, `Surface`, or even their combinations. This still leaves a lot of unknowns, but would be better than the void we have now anyway ;)

**Comment by bvssvni** [comment]
Is it possible to split this into 3 and 1+2?

**Comment by kvark** [comment]
@bvssvni certainly possible, I thought about it.
