### ISSUE TITLE
Please add me as owner to crates.io

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx-rs#683]
cc @kvark

**Comment by kvark** [comment]
Done

**Comment by bvssvni** [comment]
Thanks!

**Comment by kvark** [comment]
Not able to add you to gfx_examples:
>failed to add owners: failed to get a 200 OK response: Response {404, content-length: 35, set-cookie: cargo_session=--3c156d7a3629aa08a1a0d538832f99ea30835cc8; HttpOnly; Secure; Path=/, content-type: application/json; charset=utf-8, date: Sat, 11 Apr 2015 14:39:07 GMT, connection: keep-alive, server: nginx, via: 1.1 vegur, {"errors":[{"detail":"Not Found"}]}]
