### ISSUE TITLE
thread '<main>' panicked at 'assertion failed: output.get_mask().contains(mask)'

### ISSUE THREAD

**Issue by mitchmindtree** [gfx-rs/gfx-rs#686]
I'm running into the following panic:

```
thread '<main>' panicked at 'assertion failed: output.get_mask().contains(mask)', /Users/Mitch/.cargo/git/checkouts/gfx-rs-93bce98024942039/master/src/render/mod.rs:187
Process didn't exit successfully: `/Users/Mitch/Programming/Rust/elmesque/target/debug/examples/test` (exit code: 101)                                                  
```

[This is where the panic seems to occur](https://github.com/gfx-rs/gfx-rs/blob/master/src/render/mod.rs#L187).

I first hit it after updating [this project example](https://github.com/mitchmindtree/elmesque/blob/master/examples/test.rs) to the latest gfx-rs changes - am I initialising gfx correctly here?

I noticed the same panic occurs in both of these [gfx_graphics examples](https://github.com/PistonDevelopers/gfx_graphics/tree/master/examples) also.

**Comment by bvssvni** [comment]
I'm getting the same error.

**Comment by bvssvni** [comment]
`Frame::empty` does not set up frame buffers.

**Comment by kvark** [comment]
`Frame::empty` doesn't give you the framebuffer associated with the window, unlike what `Frame::new` used to do. Please see https://github.com/gfx-rs/gfx-rs/pull/682 and gfx examples. Note: most of the examples are now using `Canvas`, which has an output window as one of its fields. The deferred rendering example uses the output directly.

Perhaps, I should detect that the framebuffer is completely empty and print a better error message. I'll leave this issue open for this matter.
