### ISSUE TITLE
Better support for multiple factories

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#690]
## Idea

After a long sequence of evolution, we now support `Factory` as a separate thing on the gfx-rs level, and it's being generated together with the device in `gfx_device_gl::create()`. There is only one factory and no ability to create more for GL.

This somewhat makes logical sense. However, the implementation of the `gfx_device_gl::Factory` requires sharing the GL context with the device, and everything that factory needs can be taken from the device. Thus, there is no actual barrier to have multiple factories. Since they use `Rc` for referencing the context, they can't be moved to another thread, and neither can the device be.

Thus we can easily have multiple factories. We can have `create_factory()` method inside the `gfx::Device`.

## Problems
  1. On different APIs we may need different parameters to initialize a new resource factory. Consider the pool size that the factory allocates from.
  2. Unclear how to guarantee resource destruction. If a factory is created for a short session and then dies, these resources are never going to be de-allocated. We need the life times of the resources to be bound to the factory lifetime, optimally.

## Benefits

TODO
Perhaps, it's not a good idea after all....

**Comment by kvark** [comment]
Here is why this is needed. gfx_graphics could spawn its own factory from the device, thus not requiring any `update()` calls and generating glyphs on the fly. Also, the problems are not difficult to tackle:
  1. We can make this a part of GL Device only for now
  2. We can force the device to hold references to all the factories. Although, that requires sharing factories, which sucks... Alternatively, there could be a pool of "abandoned resources" that all the factories keep (a mutable) track of. When a factory dies, it transfers all the known handles into the pool. The device can scan this pool on `cleanup`.

cc @eddyb @bvssvni @csherratt

**Comment by bvssvni** [comment]
That would be nice!

**Comment by kvark** [comment]
Extending this idea even further, maybe factories don't even need to hold their resources. We can have a single pool, owned by the device, and the factories push to it when they create resources. Then, the cleanup only needs the device. I believe this is the cleanest solution, improving even what we have now, and freeing the way to support multiple factories with no effort.

**Comment by bvssvni** [comment]
This sounds like a good idea. It does not matter which object that owns the last reference as long as it is accessible with `cleanup`.

**Comment by kvark** [comment]
I bet `gfx-debug-draw` will hugely benefit from this change too. cc @stjahns

**Comment by kvark** [comment]
Fixed in #743
