### ISSUE TITLE
Get Renderer and Output together

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#693]
Such an abstraction could have convenient drawing methods that `Canvas` currently has.

**Comment by kvark** [comment]
The question is - how to name it and introduce without breaking too much.
cc @bvssvni @bjz @csherratt

**Comment by kvark** [comment]
Some random thoughts about this feature:
  1. it would certainly improve ergonomics, similar to `Canvas` but in a more widely accessible way
  2. it would have 3 generic parameters (`R`, `C`, `O`), which is a bit too many for something widely used
  3. (I forgot what I wanted to say, TODO)

**Comment by kvark** [comment]
I think I found a nice design for this!

### Stream
```rust
trait Stream<R: Resources> {
    // conveniently constrained types
    type CommandBuffer: CommandBuffer<R>;
    type Output: Output<R>,
    // the only required method to implement
    fn access(&mut self) -> (&mut Renderer<R, C>, &Output<R>);
    // actual logic in the default implementations
    fn get_aspect_ratio(&self) -> f32 {...}
    fn clear(&mut self, ClearData) {...}
    fn blit_on<X: Output<R>>(&mut self, &X, Rect, Rect, Mirror, Mask) {...}
    fn blit_to<Y: Output<R>>(&mut self, &Y, Rect, Rect, Mirror, Mask) {...}
    fn draw<B: Batch<Resources =R>>(&mut self, &B) -> Result<(), DrawError<B::Error>> {...}
    fn draw_instanced<B: Batch<Resources = R>>(&mut self, &B, InstanceCount, VertexCount)
                               -> Result<(), DrawError<B::Error>> {...}
}
```

### Generics

All of the code that renders stuff needs to work with arbitrary `Output` and doesn't directly depend on the `CommandBuffer` either. Having these as associated types here will reduce this:
```rust
fn render<R: gfx::Resources, C: gfx::CommandBuffer<R>, O: gfx::Output<R>>(&mut self, &mut Renderer<R,C>, &Output<R>) -> Something
```
into this:
```rust
fn render<R: gfx::Resources, S: gfx::Stream<R>>(&mut self, &mut S) -> Something
```
The relation is even more obvious when `R` comes as a given.

### Complexity

I was concerned that adding one more abstraction, even if optional, would complicate the class structure and confuse the users. However, I believe that `Stream` has the capability to replace `Renderer`, `CommandBuffer`, and even `Output` in most of the user code. This means that the code will be simpler, and the observed class structure will be smaller.

The user will either work with `Canvas` that implements `Stream`, or work with simple streams like this:
```rust
let mut stream = factory.create_stream(window_wrap);
stream.clear(...);
stream.draw(...);
stream.flush(&mut device);
```

### Notes

  1. It doesn't seem to make sense to have `Resources` as an associated type of `Batch`. It's typically used in `R`-constrained environment, thus just introducing more noise.
  2. Since `Stream` is going to live in render extensions, and they are growing big, it might be reasonable to move them into `extra` module (inside the same crate).

Objections? Opinions? Other thoughts?

**Comment by bvssvni** [comment]
I think `Stream` might be replaced with a less generic and more related name.
