### ISSUE TITLE
Error when compiling - std::num::from_u32

### ISSUE THREAD

**Issue by Backman** [gfx-rs/gfx-rs#697]
```
error: unresolved import `std::num::from_u32`. There is no `from_u32` in `std::num`
C:\Users\Backman\.cargo\git\checkouts\gfx-rs-93bce98024942039\master\src\render\batch.rs:234
use std::num::from_u32;
^~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `gfx`.
```
Getting this error when I'm trying to compile gfx-rs.
Rust version: rustc 1.1.0-nightly (21f278a68 2015-04-23) (built 2015-04-24)
Cargo version: cargo 0.2.0-nightly (dac600c 2015-04-22) (built 2015-04-24)

**Comment by kvark** [comment]
Thanks for the report! I suppose we need to use the `num` crate instead. A similar work has been done for the rust-1.0 branch in #689

**Comment by bvssvni** [comment]
Fixed by https://github.com/gfx-rs/gfx-rs/pull/701
