### ISSUE TITLE
The future of Canvas

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#704]
Despite it being extra useful for simplified app initialization code, we'll need it removed or heavily modified in the long run, because:
  1. `Stream` has most of its benefits yet much better isolated (no resource-related stuff)
  2. Swap buffers it not the best indicator that we can release the resources. Fences (#688) are more flexible, generic, support compute shaders, and are not bound to the context window.

Thus, we should not own the window, let Piston (or user - directly) manage it.
cc @bvssvni

**Comment by bvssvni** [comment]
Yay! I think it is a good idea to decouple rendering and resources.

**Comment by kvark** [comment]
Deprecated in #743
