### ISSUE TITLE
How to set up a stencil buffer?

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx-rs#705]
I'm trying to solve https://github.com/PistonDevelopers/gfx_graphics/issues/225

**Comment by kvark** [comment]
For the main frame, it is assumed currently that the stencil plane is present. I'm trying to extend glutin to report this properly for gfx to use (https://github.com/tomaka/glutin/pull/375), but currently enabling the detection would crash on everything but linux, so we are not using it just yet by gfx.

For the user frames, you need to have a stencil or depth/stencil plane present (either as a part of `Frame` structure, or as just a plane for cases where you don't need color buffers - `Plane` also implements `Output`).

**Comment by kvark** [comment]
Turns out there were 2 issues:
  - stencil wasn't cleared
  - window was created (by SDL2) without a stencil buffer
