### ISSUE TITLE
Building errors with rustc 1.0.0-beta 4

### ISSUE THREAD

**Issue by killkrt** [gfx-rs/gfx-rs#710]
Hi,

I've made a fresh clone of the project and this is the error that I get using `cargo build`:

```
src/lib.rs:18:1: 18:25 error: unstable feature
src/lib.rs:18 #![feature(alloc, core)]
              ^~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to previous error
Could not compile `gfx`.
```

Thank you.

System information:
Rustc: rustc 1.0.0-beta.4 (850151a75 2015-04-30) (built 2015-04-30)
OS: OS X 10.10.3 and Arch Linux (kernel 4.0.1-1)

**Comment by cmr** [comment]
Yes, gfx is not compatible with stable Rust. Use a nightly.

**Comment by kvark** [comment]
@killkrt There is a rust-1.0 branch that should be compatible. Please try it out.

**Comment by killkrt** [comment]
I've tried with the nighty and it worked! Thanks @cmr and @kvark
