### ISSUE TITLE
"This feature may not be used in the beta release channel" error

### ISSUE THREAD

**Issue by cehawkins** [gfx-rs/gfx-rs#712]
I'm new to rust and am trying to compile an example on conrod.  I'm getting this error while building gfx-rs and gfx_macro.  Is there a stable branch I can use?  The offending features are 'alloc', 'core', and 'path'.

**Comment by kvark** [comment]
@cehawkins I'm working with gfx on rust nightly. I made it compile on beta in the [rust-1.0 branch](https://github.com/gfx-rs/gfx-rs/tree/rust-1.0), if you want to stick with rust beta. However, `gfx_macros` totally requires the nightly now, and doing any serious rendering without it would be rather inconvenient.

We need someone to step up taking care of rust-1.0 release. I'm currently busy with high-level rendering, and other developers are not too active at the moment.

See #676 for more details
