### ISSUE TITLE
Poll: remove XxxHandle types

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#715]
They are now [typedeffed](https://github.com/gfx-rs/gfx-rs/blob/master/src/lib.rs#L67-L75) on `handle::Xxx`, which the users may use directly.

**Comment by cmr** [comment]
Seems like a good way to remove duplication and take advantage of namespaces. :+1:

**Comment by kvark** [comment]
I know @LaylConway was voting for this too.

**Comment by LaylConway** [comment]
This sounds like a good change :+1:

**Comment by csherratt** [comment]
![](http://cleancrypt.org/img/ripley.jpg)

**Comment by kvark** [comment]
@csherratt sweet :)

**Comment by bvssvni** [comment]
Nice! I've been waiting for this!

**Comment by kvark** [comment]
Fixed by @fkaa in #717 
For the future - please specify the dependent PRs in the comments or PR descriptions, so that it's easier to navigate between them.
