### ISSUE TITLE
Can't compile "conflicting implmentations for trait 'render::shade::Parameter'

### ISSUE THREAD

**Issue by Plasticcaz** [gfx-rs/gfx-rs#732]
Here is the output from cargo:

C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:90:1: 98:2 error: conflicting
 implementations for trait `render::shade::Parameter` [E0119]
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:90 impl<T: Clone + Into<Unifo
rmValue>, R: Resources> Parameter<R> for T {
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:91     fn check_uniform(_var:
 &shade::UniformVar) -> bool {
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:92         true //TODO
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:93     }
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:94
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:95     fn put(&self, id: Para
meterId, storage: &mut ParamStorage<R>) {
                                                                                              ...
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:110:1: 118:2 note: note confl
icting implementation here
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:110 impl<R: Resources> Parame
ter<R> for TextureParam<R> {
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:111     fn check_texture(_var
: &shade::SamplerVar) -> bool {
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:112         true
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:113     }
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:114
C:\Users\Zac\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-0.4.1\src\render\shade.rs:115     fn put(&self, id: Par
ameterId, storage: &mut ParamStorage<R>) {
                                                                                               ...
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `gfx`.

I'm trying to compile on Windows, and I'm pretty sure I'm running the latest rust beta.

I'm trying to use glutin and gfx together, but so far I'm just trying to get cargo to compile the libraries.

**Comment by kvark** [comment]
@Plasticcaz you can see that gfx-rs and gfx-examples are green on travis. Both are compiled against both rust-beta4 and the nightly. So there must be something specific about your situation. It'd be hard to believe Windows is at fault, yet verifying this would be nice (I'm on Linux).

Did you do any changes to gfx-rs? Could you post `rustc --version`?

**Comment by Plasticcaz** [comment]
PS C:\Users\Zac> rustc --version
rustc 1.0.0-nightly (be9bd7c93 2015-04-05) (built 2015-04-06)

Hmmmm... I was sure I was on stable beta... I'll update again and let you know.

**Comment by Plasticcaz** [comment]
UPDATE: It appears that several old versions of the rust compiler have not been removed when I update to a new build. I was under the impression that the installer did that.

This is almost certainly the problem. I apologize for bringing it up. Thanks for replying!

**Comment by kvark** [comment]
No worries! Glad you got it sorted out :)
