### ISSUE TITLE
Shared reference to window output backend

### ISSUE THREAD

**Issue by aepsil0n** [gfx-rs/gfx-rs#764]
I built an [output backend](https://github.com/aepsil0n/gfx_window_shared) based on shared references (both `Rc<RefCell<_>>` and `Arc<RwLock<_>>`) to implementations of Piston's `OpenGLWindow`. I hope it's okay to post this here, as it probably makes sense to integrate this into the `gfx-rs` organisation.

There is one issue compared to the other windowing backends, that comes from lack of information obtainable from OpenGLWindow, namely masks and gamma conversion are not determined from the window as in e.g. `gfx_window_glutin` but hard-coded to some default:

```rust
SharedOutput {
    // ...
    mask: gfx::COLOR | gfx::DEPTH | gfx::STENCIL,
    supports_gamma_conversion: true,
}
```

Once this is resolved, it might actually be feasible to rely on Piston's windowing abstraction in general.

**Comment by kvark** [comment]
@aepsil0n sweet! Could you move it under `PistonDevelopers`?

**Comment by aepsil0n** [comment]
oh, right, that makes sense, too… I'll do that.

**Comment by aepsil0n** [comment]
Ok, so here it is: https://github.com/PistonDevelopers/gfx_window_shared
