### ISSUE TITLE
Consolidate the projects

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx-rs#768]
A bit of history:
  - `gfx-rs` started as a single project, having everything (renderer, device, macros, even windowing stuff) under one repository in different modules
  - macros were moved out
  - eventually, associated types got supported by Rust, and we were able to move the device out
  - examples followed the suit
  - we ended up following Piston organization style and created a repository per project. More and more showed up, mostly bearing just a bit of function.

Currently we have 10 projects closely related to `gfx-rs`, and this number doesn't include `gfx_scene` or `genmesh`. This confuses newcomers and throttles our ability to do cross-project changes. 

Unexpectedly, a new style of organization [showed up](https://github.com/gfx-rs/gfx_scene/pull/43#issuecomment-110984929) to be effective in `gfx_scene` and `claymore`: gather all relevant projects under one roof and use both `path = ` and `version =` in the dependencies. As it turned out, this scheme has proper crates dependencies and publishing doesn't require any temporary changes. I propose to follow this scheme for `gfx-rs` as well to get:
  - easier branching (especially for new major versions)
  - easier pull requests with no/less dependencies
  - faster and more secure builds (single `cargo test` does everything)
  - less confusion for the users (`gfx-rs` organization would have 4 projects instead of 13)
  - single issue database

Paint me red and stuff, but I don't see the downsides. Note that we can do it right now without breaking anything, since users now depend on `crates.io`. Here is how I see the consolidated repo:
```python
gfx/ # does it make sense to keep it gfx-rs?
  examples/ # gfx_examples/bin
  src/
    aux/
       gl/ # gfx_gl
    backend/
      gl/ # gfx_device_gl
      dummy/ # gfx_device_dummy
      vulkan/ # gfx_device_vulkan
    core/ # gfx-rs
    draw_state/ # arguable, lets hear @bvssvni
    window/
      glfw/ # gfx_window_glfw
      glutin/ # gfx_window_glutin
    main.rs # empty, just to depend on all the crates
  info/ # additional documentation, like what we have in gfx-rs/wiki
  .travis.yml # there can be only one
```

Summoning @gfx-rs/developers for discussion!

**Comment by csherratt** [comment]
This is similar to how we started.

I don't have a problem with this, but I want to preserve the commit history of all our projects. Not sure how to do with when merging git repos but there is bound to be a stackoverflow for it.

**Comment by kvark** [comment]
@csherratt Good point.  `gfx_device_gl` in particular has some history. On the other hand, most of the changes reflect the associated gfx-rs PRs.

**Comment by fkaa** [comment]
Not a @gfx-rs/developers but i think it sounds great! I didn't exactly have a good time making a PR for 5 separate gfx repos at the same time...

**Comment by kvark** [comment]
@fkaa fixed!

**Comment by kvark** [comment]
Small issue: `gfx_gl` uses git submodules, which would need to be moved into the whole repo. I don't like this idea, so leaving `gfx_gl` aside for now.

**Comment by kvark** [comment]
Another issue: tests for dependent projects are not started automatically by `cargo.test`. We may need to pull all the tests into the root crate.

**Comment by bjz** [comment]
Don't have a problem with this, but I echo the comments about preserving git history.

**Comment by bjz** [comment]
I wounder if this should be a medium or hard, given the difficulty of the repo merger.

**Comment by kvark** [comment]
@bjz thanks for coming in!

Since we use 'hard' for the most difficult issues (like, implement DX backend), this one deserves a vagua `average` rating.

I'll redo the PR with preserved history, not sure how painful it's going to be though. If you want to try it yourself, please give me a short nod so that we don't duplicate this exciting work.

**Comment by kvark** [comment]
Heads up - SO [answer](http://stackoverflow.com/questions/1683531/how-to-import-existing-git-repository-into-another) seems to be working fine, I'm half-way through the change.

**Comment by csherratt** [comment]
:tada: Wonderful @kvark

**Comment by bvssvni** [comment]
Nice!

**Comment by kvark** [comment]
@bvssvni I was thinking if you would consider the unification of some degree for Piston repositories. Their diversity and number often seemed to be a source of confusion.
