### ISSUE TITLE
Move gl device implementation into separate crate

### ISSUE THREAD

**Issue by bjz** [gfx-rs/gfx-rs#80]
I am having trouble understanding it. It would be great if it were more decoupled from the common `device` interface.

**Comment by kvark** [comment]
@bjz I believe you are working on this one?

**Comment by bjz** [comment]
I was working on it, but was blocked by the associated item stuff.

**Comment by kvark** [comment]
Posting your comment, assuming it was about this issue:
> Arg, trying to get associated types working with handles
but I am running into issues
I end up needing to pass the Device as a type parameter around
and the CommandBuffer trait needs the handle types
so CommandBuffer needs Device as a type parameter
but that ends in type checker recursion and blowing up rustc's stack
:pensive:

**Comment by kvark** [comment]
@bjz So you are running into a type dependency recursion? Come back to gitter, when you have a moment, to share more info. Perhaps, you could push your branch for me to check out.
